### ISSUE TITLE
GA SDK release plan has been proposed to Private Preview

### ISSUE THREAD

**Issue by josefree** [test-repo-billy/azure-rest-api-specs#2836]
![image](https://user-images.githubusercontent.com/18413981/211991419-baf38005-4938-420b-bdf4-8011d2904c6f.png)

**Comment by josefree** [comment]
![image](https://user-images.githubusercontent.com/18413981/211992142-6f526705-da43-4b74-9ebe-b5f64bedd400.png)

**Comment by josefree** [comment]
![image](https://user-images.githubusercontent.com/18413981/211992203-070a738a-5350-4cfd-891c-b3d1f0f0065c.png)

**Comment by live1206** [comment]
Could not reproduce it, I got the expected info:


![Image](https://user-images.githubusercontent.com/5196139/212219105-2ff04189-5773-440a-8fa5-4d13afe4c7f9.png)

@josefree Could you provide the data you filled in on the initial page of `Create a Release Plan`? Did you specify the target phase to `GA` instead of `Public Preview`?
